### ISSUE TITLE
Usare decentemente i nomi per i commit

### ISSUE THREAD

**Issue by jackrendor** [CalypsoPi/Website#2]
Sto vedendo un sacco di confusione nel repo. Ci sono un bordello di commit con scritto "up" e "push" e sta cosa non va bene. 

Cercate di raggruppare i commit (e.g.: modificare più file per poi fare un singolo commit) e di utilizzare messaggi sensati per ogni commit, così da essere più facile capire cosa sta succedendo e l'avanzamento del progetto.

Un esempio di commit decente lo potete trovare qua: https://github.com/jackrendor/jwpf/commits/master

**Comment by Okazakee** [comment]
Hai ragione, ultimamente ho rimediato, chiudo issue.
